### ISSUE TITLE
Fails when used with concurrent async

### ISSUE THREAD

**Issue by AntVil** [patrick-zippenfenig/ClickHouseVapor#7]
when used with concurrent async methods (eg `async let`, `withThrowingTaskGroup`, ...) this error gets throws:

> AsyncKit/EventLoopGroupConnectionPool.swift:296: Assertion failed: ConnectionPool.shutdown() was not called before deinit.
error: Exited with signal code 4

**Comment by patrick-zippenfenig** [comment]
Hi Anton! Glad to hear from you again and thanks for the report+PR. IIRC the pool locking code is also used in other vapor database connectors that could be affected by this issue. 

Fix released in `1.3.1`
